### ISSUE TITLE
should we add DataStore API support to this provider?

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop-provider-ckan#4]
about a month ago i did some work trying to integrate a few of the City of Charlotte's existing flat tables from Accela into Koop and noticed that [koop-ckan](https://github.com/chelm/koop-ckan) doesn't seem to include support for CKAN's [DataStore API](http://docs.ckan.org/en/847-new-theming-docs/datastore.html#the-datastore-api).

i was able to get things running in my own forked feature branch ([here](https://github.com/jgravois/koop-ckan/commit/4896e7a34e3d603221899660525e82b2e7328b90)) by hardcoding the appropriate resource url path (and even utilized Proj4 to reproject northings and eastings from the table on the fly), but the project left me w/ a few questions.
1. why doesn't the output i'm writing draw in AGOL?
2. would it be worthwhile to try and integrate dynamic support for the DataStore API into this provider? is it more of an Accela thing?

an example of my output:
http://whispering-temple-3513.herokuapp.com/ckan/accela/e53f0901-62fb-443d-a22c-9a5afc851aef/

the same data in Accela:
http://www.civicdata.com/api/3/action/datastore_search?resource_id=e53f0901-62fb-443d-a22c-9a5afc851aef
http://www.civicdata.com/datastore/dump/e53f0901-62fb-443d-a22c-9a5afc851aef

**Comment by chelm** [comment]
@jgravois Okay - the ckan provider was pretty basebones as Im sure you found out. So Im not up to speed on the datastore API. 

With regard to your data not showing up. I am not entirely sure what might be going on, but are you aware X/Y pairs backwards? It looks like you're y values are around -80 which would be really far south. 

Also now im getting an error on the example link. http://whispering-temple-3513.herokuapp.com/ckan/accela/e53f0901-62fb-443d-a22c-9a5afc851aef/FeatureServer/0/query

**Comment by jgravois** [comment]
good catch on the lat/longs.  i feel like i tried both ways and am not surprised i ended up with them backwards.  

w/ regard to the error, the server must have crashed.  i just reregistered my provider, and its back up and running now.  `curl --data "host=http://www.civicdata.com&id=accela" http://whispering-temple-3513.herokuapp.com/ckan`

**Comment by chelm** [comment]
@jgravois The other reason I think its not rendering is cause there is not a Object ID field in the fields.

**Comment by jgravois** [comment]
i was hoping the one that koop tacks onto the end of the list of attributes would be all i needed...

**Comment by chelm** [comment]
right and for some reason it has the wrong type. So there's the bug. It needs to be `esriFieldTypeOID` not `esriFieldTypeInteger`

**Comment by jgravois** [comment]
ahh.. gotcha.  thanks for the lead!  i'll see if i can fix and let you know the outcome.
