### ISSUE TITLE
readme sample urls are out of date

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop-provider-ckan#7]
we need to remove references to [rwlabs/ourairports-ind](https://data.hdx.rwlabs.org/ourairports-ind) (actual dataset can be found [here](https://data.hdx.rwlabs.org/dataset/ourairports-ind))

i'd like to replace with this [toilet dataset](http://www.civicdata.com/dataset/national-public-toilet-map-data/resource/8a7cc861-b49b-4506-872e-2153aff575c6), but i'm having trouble accessing the dataset via koop too.
#### my two best guesses
1. the koop provider doesn't know how to fetch remote resources (ie: http://civicdataprod1.cloudapp.net/storage/f/2014-07-09T17%3A35%3A39.552Z/toilet-locations.csv)
2. perhaps still a lack of support for CKANs [DataStore](https://github.com/koopjs/koop-ckan/issues/4) API (i feel like you said you added that though)

**Comment by chelm** [comment]
@jgravois Yes I remember talking about the datastore API and that should be working. Looking into it.

**Comment by chelm** [comment]
@jgravois With the latest koop-ckan (v0.0.9) this dataset works. http://koop.dc.esri.com/ckan/civicdata/national-public-toilet-map-data/FeatureServer/0/query 

However, the coordinates looks all messed up, they are in the wrong hemishpere

**Comment by chelm** [comment]
oh, its Australia im looking at.

**Comment by jgravois** [comment]
my bad for not upgrading to the latest and greatest `koop-ckan` before logging this, but i can still repro the error after cloning `koop-sample-app` from scratch, and pointing at a brand new PostGIS instance.
```
getaddrinfo ENOTFOUND
```
perhaps there is some other minor version mismatch between koop.dc.esri and the sample?
